### ISSUE TITLE
Psutil doesn't install on linux.

### ISSUE THREAD

**Issue by clin88** [uber/mutornadomon#17]
Downloading/unpacking psutil
  Running setup.py egg_info for package psutil

    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: manifest_maker: MANIFEST.in, line 18: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

Installing collected packages: psutil
  Running setup.py install for psutil
    building 'psutil._psutil_linux' extension
    cc -O2 -fPIC -Wimplicit -DPSUTIL_VERSION=311 -I/home/uber/populous/pypyenv/include -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o
    psutil/_psutil_linux.c:12:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'cc' failed with exit status 1
    Complete output from command /home/uber/populous/pypyenv/bin/pypy -c "import setuptools;__file__='/home/uber/populous/pypyenv/build/psutil/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-KDns8r-record/install-record.txt --single-version-externally-managed --install-headers /home/uber/populous/pypyenv/include/site/python2.7:
    running install

running build

running build_py

running build_ext

building 'psutil._psutil_linux' extension

cc -O2 -fPIC -Wimplicit -DPSUTIL_VERSION=311 -I/home/uber/populous/pypyenv/include -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o

psutil/_psutil_linux.c:12:20: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'cc' failed with exit status 1

----------------------------------------
Command /home/uber/populous/pypyenv/bin/pypy -c "import setuptools;__file__='/home/uber/populous/pypyenv/build/psutil/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-KDns8r-record/install-record.txt --single-version-externally-managed --install-headers /home/uber/populous/pypyenv/include/site/python2.7 failed with error code 1 in /home/uber/populous/pypyenv/build/psutil

**Comment by Roguelazer** [comment]
You usually need a package installed system wide named something like "python-dev". Look in yum/apt/portage/your friendly local system package manager.

-- 
James Brown, currently mobile

**Comment by clin88** [comment]
Thanks @Roguelazer ! I googled around a bit and I just needed pypy-dev.
